spring.application.name=task-management
server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.mongo.enabled=true

#JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}