spring.data.mongodb.uri=mongodb://localhost:27017/task-management-local?serverSelectionTimeoutMS=3000&connectTimeoutMS=3000&socketTimeoutMS=3000&retryWrites=false
spring.data.mongodb.database=task-management
