[build]
  base    = "task-management-frontend"
  publish = "dist/Task-Manager"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://enterprise-task-management-backend.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
